
services:
  # 1. Django App Container
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # 정적 파일 볼륨 공유
    env_file:
      - .env.prod
    depends_on:
      - db

  # 2. PostgreSQL Container
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data # DB 데이터 영구 보존
    env_file:
      - .env.prod

  # 3. Nginx Container
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles  # Django가 모은 정적 파일을 읽음
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
