apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - itformation.p-e.kr
    secretName: django-tls-certificate
  rules:
  - host: itformation.p-e.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # 트래픽을 Nginx Service로 전달
            name: nginx-service
            port:
              # Nginx Service의 포트 (Nginx Pod의 80번 포트)
              number: 80
